services:
  nginx:
    image: nginx
    depends_on:
      - php74
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/php_farm/fpm74:/etc/nginx/fpm74
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ${WWW}:/www
  php74:
    # build: ./build/php/php74
    image: haiquang9994/php74-fpm
    volumes:
      - ${WWW}:/www
      - ./php/php74/php.ini:/usr/local/etc/php/php.ini
    deploy:
      mode: replicated
      replicas: 3
  redis:
    image: redis
    volumes:
      - ./redis/data:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306
    volumes:
      - ${WWW}/sql:/sql
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/.my.cnf:/root/.my.cnf